### ISSUE TITLE
Using as a dynamic loaded package

### ISSUE THREAD

**Issue by darleybarreto** [anderslanglands/ustr#11]
Hi, I am **really** new to Rust and I was wondering what would I have to change in order to compile the package to a `.so` and use it like in CPython? I think I would have to initialize, from Python, the Hash on memory first with something like `lazy_static!` and then drop after using it, right? Also what packages would you recommend to replace those using std?

Thanks in advance!

**Comment by anderslanglands** [comment]
Hi Darley, i haven’t tried using it from python but in theory all you need to do is bring the C API into the crate and compile it as a dynamic library to be able to use it with ctypes. 

To do that you’d just need to add the following lines to lib.rs to compile in the C API:
```
pub mod ustr_extern;
pub use ustr_extern::*;
```

then to compile the crate as a dynamic library, just add the following to Cargo.toml:

```
[lib]
crate-type=“cdylib”
```

This will now give you “libustr.so” which you should be able to load with ctypes. You shouldn’t need to initialise the storage - that should be done automatically when you first call ustr(). 

Let me know how you get on!

**Comment by darleybarreto** [comment]
A really simple usage from CPython would be like the one bellow
```python
from cffi import FFI
ffi = FFI()
ffi.cdef("""
    char * load_str(char *);
    void free_str(char *);
""")
p_str = "I will go down to the rabbit hole!".encode("utf-8")
size = len(p_str)
lib = ffi.dlopen("path/to/rustlib.so")
pointer = lib.load_str(p)
p_str_2 = ffi.buffer(pointer,size)[:].decode("utf-8") # a perfect string
lib.free_str(pointer) # freeing 
```
And the `rustlib.so` is
```rust
use core::{ptr,str};
use ustr::Ustr;
use cstr_core::{CString, CStr, c_char};

#[no_mangle]
pub extern "C" fn load_str(d_ptr: *mut c_char) -> *mut c_char {
    // Based on https://bheisler.github.io/post/calling-rust-in-python/

    if d_ptr.is_null() {
        return ptr::null_mut();
    }
    let data = unsafe { CStr::from_ptr(d_ptr).to_bytes() };
    
    match str::from_utf8(data){
        Ok(data_str) => {
            let gc_string = Ustr::from(data_str);
            CString::new(gc_string.as_str()).unwrap().into_raw()
        },
        Err(e) => {
            println!("Error while converting raw pointer back to str: {}", e);
            ptr::null_mut()
        },
    }
}

#[no_mangle]
pub extern "C" fn free_str(d_ptr: *mut c_char) {
    if d_ptr.is_null() {
        return;
    }  

    let data = unsafe { CStr::from_ptr(d_ptr).to_bytes() };

    match str::from_utf8(data){
        Ok(data_str) => {
            let gc_string = Ustr::from(data_str);
        },
        Err(e) => {
            println!("Error on dropping while converting raw pointer back to str: {}", e);
        },
    }
}
```
Since I am new to rust, I saw [this](https://github.com/Storyyeller/easy_strings/blob/master/src/lib.rs#L19) implementation and thought that I should do something similar to allocate the HashMap on memory until I manually deallocate it calling another rust function, i.e., `destroy_hash`. 
So when I call `load_str` from Python for the first time, the cache will be created and when I free the last string with `free_str` it will be destroyed, right?

**Comment by anderslanglands** [comment]
The Ustr cache is never freed. It's allocated automatically and freed when the process exits, you don't need to worry about it at all.

I've created a simple repo here: https://github.com/anderslanglands/ustr_capi showing how to build ustr into a .so and then loading and using it from python using cffi.

**Comment by darleybarreto** [comment]
Thank you so much for you help and clarifying this to me!
