### ISSUE TITLE
Why Ustr does not derive Ord?

### ISSUE THREAD

**Issue by macprog-guy** [anderslanglands/ustr#12]
Hello, I've been using this excellent library in a project of mine and when I wanted sort a Vec<Ustr>, it was telling me that Ustr does not implement Ord! Ustr already implements Eq and PartialEq. All that needed is to derive Ord on live 157 of lib.rs.
Cheers,

**Comment by anderslanglands** [comment]
Thanks! That was an oversight on my part. I've pushed a fix and a test and once that's gone through CI this will be published to crates.io as version 0.7.0

**Comment by anderslanglands** [comment]
CI passed and publish is up. Thanks for reporting!

**Comment by macprog-guy** [comment]
That was quick! Excellent thank.
