### ISSUE TITLE
Update version of parking_lot dependency

### ISSUE THREAD

**Issue by mverleg** [anderslanglands/ustr#17]
Thanks for creating ustr, it's very nice!

Running `cargo audit` currently flags my project because of an issue that used to exist in `lock_api` ([rustsec](https://rustsec.org/advisories/RUSTSEC-2020-0070)), and which can cause data races.

The issue in `lock_api` has been fixed, and `parking_lot` has updated to that version. The master branch of `ustr` has in turn updated to the latest `parking_lot`, but the version [on crates.io](https://crates.io/crates/ustr/0.7.0/dependencies) is behind.

If it's not too minor, could a new version be released with latest dependencies, so that is not susceptible to data races?

**Comment by anderslanglands** [comment]
Thanks for the reminder! I've now published v0.8.0 https://crates.io/crates/ustr
