### ISSUE TITLE
Add serde support

### ISSUE THREAD

**Issue by anderslanglands** [anderslanglands/ustr#2]
Implement serde::{Serialize, Deserialize} for StringCache

**Comment by anderslanglands** [comment]
Implemented on serde branch. Could use some more testing before merging to master

**Comment by luke-titley** [comment]
Hey,
The StringCache serialization is cool, and I think I'll find it super useful soon, but I was looking more for just the serde traits for the Ustr struct itself. This means I can have Ustr fields in my serializable structs.

It could be that I've missed something, but at the moment I don't think it's possible to do that, without my manually implementing the traits for any structs that use Ustr.

I've had a quick go at implementing them on my fork. It could be more optimal, but for my uses it's enough. I've sent you a merge request.
