### ISSUE TITLE
Inconsistent Ord and PartialOrd

### ISSUE THREAD

**Issue by zigazeljko** [anderslanglands/ustr#20]
The derived `Ord` is inconsistent with the `PartialOrd`, since it does not implement lexicographical ordering.

By the way, it seems the compiler did already detect this issue, but #10 silenced the warning instead of fixing it.

**Comment by mverleg** [comment]
I'm running into this bug. Has the fix be published to crates.io? Or otherwise can it be released soon @anderslanglands ? Thanks!

According to [docs](https://docs.rs/ustr/0.8.1/src/ustr/lib.rs.html#158), v0.8.1 still has Ord derived instead of the impl from #21.
