### ISSUE TITLE
Is there an easy way to use Ustrs as integers?

### ISSUE THREAD

**Issue by loxs** [anderslanglands/ustr#26]
Hi and thanks for the great library!

I need to use `Ustr` backed categorical values in a ML library that only supports numeric values for categories. I see that I can easily retrieve the precomputed hash via `Ustr::precomputed_hash` and I can use this value as id, but when I get my results back I won't know which id is which Ustr. Or at least I cannot figure it out by briefly exploring the code.
Is there a straightforward way to do this or should I just store my own map of ids to Ustrs?

**Comment by anderslanglands** [comment]
Yeah you'd need to store your own map if you want to use the hash. Each Ustr is essentially just a pointer, so you could convert the pointer (as_char_ptr()) to a usize to get a numeric value, then mem::transmute() it back to a Ustr again. The resulting value will obviously change every run of the program, so if you need the values to persist between runs (i.e. if you're serializing them) you'll need to use the map approach.
