### ISSUE TITLE
Symbols always resolve to an empty str on wasm32-unknown-unknown

### ISSUE THREAD

**Issue by QuinnWilton** [anderslanglands/ustr#33]
Hi again!

I spoke a little too soon in my last issue, and even with an updated `parking_lot`, I haven't quite been able to get things to work on `wasm32-unknown-unknown`, and symbols always end up resolving to an empty `&str`.

I've created a minimal reproduction [here](https://github.com/QuinnWilton/ustr-wasm-bug). The code should be fairly straightforward, but it just exports a `reproduce` function to Javascript, which when called, logs `Ustr::from("test").as_str()` to the browser's console. You'll note that an empty string is logged.

I imagine this has something to do with the pointer tagging scheme you employ, but I haven't investigated enough to be sure.

In the meantime, I've swapped out for a simpler string interning crate in my code, so this isn't a blocking issue for me or anything, but I at least wanted to raise it in case you had any ideas, or anyone else gets stuck on the same thing :)

Thanks again for the crate! If this ever gets resolved, I'd love to switch back to `Ustr`, because it really is an impressively fast piece of code.

**Comment by anderslanglands** [comment]
Thanks for the repro case! I was a bit confused by your last issue as the parking lot bump was already published in 0.8!

I'm afraid I have zero experience with WASM or web tech in general so it's unlikely I'll be able to do too much about this myself in the near term at least.

**Comment by QuinnWilton** [comment]
> Thanks for the repro case! I was a bit confused by your last issue as the parking lot bump was already published in 0.8!

Was it? Unless I'm misunderstanding the crates.io UI (which is very possible, I'm new to Rust!), 0.9 and 0.8 both depend on `parking_lot ^0.11`, whereas it's `0.12` that ends up being necessary to build things successfully: https://crates.io/crates/ustr/0.9.0/dependencies

> I'm afraid I have zero experience with WASM or web tech in general so it's unlikely I'll be able to do too much about this myself in the near term at least.

No worries at all!

**Comment by bouk** [comment]
Got a fix here: https://github.com/anderslanglands/ustr/pull/34
