### ISSUE TITLE
`serde` feature doesn't work

### ISSUE THREAD

**Issue by Seeker14491** [anderslanglands/ustr#36]
Per the changelog, `v0.10` of this crate renames the `serialization` feature to `serde`. However, this change was only made in `Cargo.toml`—the library code (and docs/readme) still references the `serialization` feature. Therefore, the feature is unusable.

**edit:** As a side note, I just noticed the readme and crate docs mention a `serialize` feature, but the feature was actually called `serialization`.

**Comment by twitu** [comment]
I've stumbled upon the same issue. Apparently the released `0.10` version doesn't have the `serialization` -> `serde` change.

**Comment by pacak** [comment]
This commit is missing from the released version https://github.com/anderslanglands/ustr/commit/c78ddc25300c4720ffcb5f8ddef6028cef14535f

**Comment by MForster** [comment]
@anderslanglands Would you mind pushing a new version to crates.io with the fix included?
