### ISSUE TITLE
Choose hash function

### ISSUE THREAD

**Issue by Boshen** [anderslanglands/ustr#39]
https://github.com/anderslanglands/ustr/issues/3 mentioned that ahash is performant enough, but it has other characteristics (inconsistent hash) which are not desirable for us - https://github.com/web-infra-dev/rspack/issues/5481

Everything still works when I switched ahash to fxhash https://github.com/anderslanglands/ustr/compare/master...Boshen:ustr-fxhash:master

Is it worthwhile to add more popular hash functions as feature toggles or should I just keep and publish the fork?

---

We may also need to benchmark again with the latest changes from ahash, since the current benchmark is done a few years ago.

**Comment by kornelski** [comment]
`Ustr<H = ahash::AHasher>` default is relatively easy to add, but then it accesses the global `STRING_CACHE` using hash result. I don't know how to elegantly partition that.

**Comment by Boshen** [comment]
True ... `ustr` is a global object.

Given the use case is niche, I released https://crates.io/crates/ustr-fxhash for anyone who needs a fxhash replacement.
