### ISSUE TITLE
Example how to reuse in other language - C/C++, etc?

### ISSUE THREAD

**Issue by malkia** [anderslanglands/ustr#7]
Would it be appropriate to have one?

**Comment by anderslanglands** [comment]
Yes it would. I’ve been meaning to add a .h for that too.

**Comment by anderslanglands** [comment]
This is done in [this commit](https://github.com/anderslanglands/ustr/commit/631852e6fe429afaea0d92add465786965464571l)

**Comment by malkia** [comment]
Thank you so much! I'll close the issue!

**Comment by anderslanglands** [comment]
Please let me know how you get on - I haven't directly tested the code in
there (it's ripped out of another project where I am using it), so if you
find any issues or can think og any improvements to the C/++ interface I'd
love to hear your thoughts.
